publish_mode: editorial_workflow
media_folder: "public/images" 
public_folder: "/images" 
backend:
  name: github
  repo: aboumicho/furreur_website
  branch: master 
collections:
  - name: "manteau" # Used in routes, e.g., /admin/collections/manteau
    label: "Manteau" # Used in the UI
    folder: "clothes/manteau" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      #- {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Sizes", name: "sizes", widget: "list", default: ["small"], allow_add: true}
      - {label: "Colors", name: "colors", widget: "list", default: ["black"]}
      - {label: "Body", name: "body", widget: "markdown"}